twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/fields.html.twig']
    globals:
        profile_images: '%profile_images%'

when@test:
    twig:
        strict_variables: true
        
