version: "3.8"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3309 # this is needed if we want to overwrite default 3306 port due to that is already in use
    ports:
      - 3309:3309
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025